Output output.mp4

Require jam
Require gum

Set Shell "bash"
Set FontSize 24
Set Width 1200
Set Height 600
Set KeyStrokes Show

Type "jam --config-file ~/code/jam/rsrc/configs/demo.yml"
Sleep 500ms
Enter
Sleep 2s
Type "b"
Sleep 1s
Type "d"
Sleep 1s
Type "?"
Sleep 3s
Backspace
Sleep 1s
Type "?"
Sleep 1s
Type "."
Sleep 4500ms 
Type "jam --config-file ~/code/jam/rsrc/configs/demo.yml"
Sleep 300ms 
Enter
Sleep 1500ms 
Type "r"
Sleep 2s
